apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rapidpass-api.fullname" . }}
  labels:
    app: {{ template "rapidpass-api.name" . }}
    chart: {{ template "rapidpass-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: {{ .Release.Revision | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rapidpass-api.name" . }}
      chart: {{ template "rapidpass-api.chart" . }}
  template:
    metadata:
      labels:
        app: {{ template "rapidpass-api.name" . }}
        chart: {{ template "rapidpass-api.chart" . }}
        revision: {{ .Release.Revision | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ template "rapidpass-api.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
