apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rapidpass-api.fullname" . }}
  labels:
    app: {{ template "rapidpass-api.name" . }}
    chart: {{ template "rapidpass-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  RAPIDPASS_PG_HOST: {{ .Values.config.postgres.host | b64enc }}
  RAPIDPASS_PG_PORT: {{ .Values.config.postgres.port | b64enc }}
  RAPIDPASS_PG_DATABASE: {{ .Values.config.postgres.database | b64enc }}
  RAPIDPASS_PG_USERNAME: {{ .Values.config.postgres.username | b64enc }}
  RAPIDPASS_PG_PASSWORD: {{ .Values.config.postgres.password | b64enc }}
  RAPIDPASS_SMTP_HOST: {{ .Values.config.smtp.host | b64enc }}
  RAPIDPASS_SMTP_PORT: {{ .Values.config.smtp.port | b64enc }}
  RAPIDPASS_SMTP_USERNAME: {{ .Values.config.smtp.username | b64enc }}
  RAPIDPASS_SMTP_PASSWORD: {{ .Values.config.smtp.password | b64enc }}
  RAPIDPASS_SMTP_AUTH_ENABLED: {{ .Values.config.smtp.auth | b64enc }}
  RAPIDPASS_SMTP_TLS_ENABLED: {{ .Values.config.smtp.tls | b64enc }}
  RAPIDPASS_SEMAPHORE_URL: {{ .Values.config.semaphore.url | b64enc }}
  RAPIDPASS_SEMAPHORE_KEY: {{ .Values.config.semaphore.key | b64enc }}
  RAPIDPASS_QRMASTER_SKEY: {{ .Values.config.qrmaster.skey | b64enc }}
  RAPIDPASS_QRMASTER_CONTROLKEY: {{ .Values.config.qrmaster.controlkey | b64enc }}
  RAPIDPASS_JWT_APPROVER_SECRET: {{ .Values.config.jwt.approverSecret | b64enc }}
  RAPIDPASS_JWT_CHECKPOINT_SECRET: {{ .Values.config.jwt.checkpointSecret | b64enc }}
