stages:
  - build
  - package
  - deploy

build-jar:
  stage: build
  image: openjdk:15-jdk-alpine
  script:
  - ./mvnw test
  - ./mvnw package -Pliquibase -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/

package-image-dev:
  stage: package
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:latest .
  - docker push dctx/rapidpass-api:latest
  only:
  - develop
  dependencies:
  - build-jar

package-image-test:
  stage: package
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:test .
  - docker push dctx/rapidpass-api:test
  only:
  - test
  dependencies:
  - build-jar

package-image-prod:
  stage: package
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:${PROD_VERSION} .
  - docker push dctx/rapidpass-api:${PROD_VERSION}
  only:
    - master
  dependencies:
  - build-jar