stages:
  - test
  - package
  - deploy

Run Unit Tests:
  stage: test
  image: openjdk:8-jdk-alpine
  script:
  - ./mvnw test

Publish Docker Image:
  stage: package
  image: docker:18.09
  services:
  - docker:18.09-dind
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker pull dctx/rapidpass-api:latest
  - docker build -t dctx/rapidpass-api:latest .
  - docker push dctx/rapidpass-api:latest
  only:
  - develop

Deploy to Test Environment:
  stage: deploy
  image: alpine/helm:2.15.2
  before_script:
  - helm init --client-only  
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  script:
  - helm dep update helm/rapidpass-api
  - helm upgrade rapidpass-api-test --install --namespace rapidpass-api-test --values config/test-values.yaml helm/rapidpass-api
  only:
  - develop
