stages:
  - build
  - package
  - deploy

build-jar:
  stage: build
  image: openjdk:15-jdk-alpine
  script:
  - ./mvnw test
  - ./mvnw package -Pliquibase -Dmaven.test.skip=true
  artifacts:
    paths:
    - target/

package-image-dev:
  stage: package
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:latest .
  - docker push dctx/rapidpass-api:latest
  only:
  - develop
  dependencies:
  - build-jar

package-image-test:
  stage: package
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:test .
  - docker push dctx/rapidpass-api:test
  only:
  - test
  dependencies:
  - build-jar

package-image-prod:
  stage: package
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
  - docker build -t dctx/rapidpass-api:${PROD_VERSION} .
  - docker push dctx/rapidpass-api:${PROD_VERSION}
  only:
    - master
  dependencies:
  - build-jar


deploy-dev:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v1.16.2-v2.15.2
  before_script:
  - helm init --client-only  
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - mkdir -p ~/.kube
  - cp ${KUBECONFIG} ~/.kube/config
  script:
  - helm dep update helm/rapidpass-api
  - helm upgrade rapidpass-api-dev --install --namespace rapidpass-api-dev --values config/dev-values.yaml --set config.smtp.username=${SMTP_USERNAME} --set config.smtp.password=${SMTP_PASSWORD} --set config.semaphore.key=${SEMAPHORE_KEY} --set config.jwt.approverSecret=${APPROVER_SECRET} --set config.jwt.checkpointSecret=${CHECKPOINT_SECRET} --set config.qrmaster.skey=${QR_KEY} --set config.qrmaster.controlkey=${CONTROL_KEY} helm/rapidpass-api
  only:
  - develop

deploy-test:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v1.16.2-v2.15.2
  before_script:
  - helm init --client-only  
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - mkdir -p ~/.kube
  - cp ${KUBECONFIG} ~/.kube/config
  script:
  - helm dep update helm/rapidpass-api
  - helm upgrade rapidpass-api-test --install --namespace rapidpass-api-test --values config/test-values.yaml --set config.smtp.username=${SMTP_USERNAME} --set config.smtp.password=${SMTP_PASSWORD} --set config.semaphore.key=${SEMAPHORE_KEY} --set config.jwt.approverSecret=${APPROVER_SECRET} --set config.jwt.checkpointSecret=${CHECKPOINT_SECRET} --set config.qrmaster.skey=${QR_KEY} --set config.qrmaster.controlkey=${CONTROL_KEY} helm/rapidpass-api
  only:
  - test

deploy-prod:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v1.16.2-v2.15.2
  before_script:
  - helm init --client-only
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - mkdir -p ~/.kube
  - cp ${KUBECONFIG} ~/.kube/config
  script:
  - helm dep update helm/rapidpass-api
  - helm upgrade rapidpass-api --install --namespace rapidpass-api --values config/prod-values.yaml --set config.smtp.username=${SMTP_USERNAME} --set config.smtp.password=${SMTP_PASSWORD} --set config.semaphore.key=${SEMAPHORE_KEY} --set config.postgres.username=${PROD_DB_USERNAME} --config.postgres.password=${PROD_DB_PASSWORD}  --set config.jwt.approverSecret=${PROD_APPROVER_SECRET} --set config.jwt.checkpointSecret=${PROD_CHECKPOINT_SECRET} --set image.tag=${PROD_VERSION} helm/rapidpass-api
  only:
  - master
