version: "3"
services:
  rapidpass:
    container_name: rapidpass_api
    build: .
    image: dctx/rapidpass-api:latest
    restart: always
    ports:
    - 8080:8080
  db:
    container_name: rapidpass_db
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: dctx
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rapidpass
    ports:
    - 5432:5432
  swagger:
    image: swaggerapi/swagger-ui:v3.25.0
    container_name: rapidpass_swagger
    restart: always
    environment:
      URL: http://localhost:8080/api/v1/spec
    ports:
      - "9999:8080"

