{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rapidpass-api.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "rapidpass-api.name" . }}
    chart: {{ template "rapidpass-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "swaggerui.fullname" . }}
          servicePort: 80
        path: /
      - backend:
          serviceName: {{ template "rapidpass-api.fullname" . }}
          servicePort: 80
        path: /api/v1
        pathType: Exact

{{- end }}
