spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat

  mail:
    host: smtp.mailgun.org
    port: 587
    username: rapidpass@talino.mg.amihan.net
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.JsonDeserializer
      group-id: group_id
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  topic:
    name: requests
    partitions-num: 3
    replication-factor: 1

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

testMobile: 09171234567
testEmail: test@gmail.com
