spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat

  mail:
    host: smtp.mailgun.org
    port: 587
    username: rapidpass@talino.mg.amihan.net
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

testMobile: 09171234567
testEmail: test@gmail.com

security.enabled: true

jwt:
  secrets:
    - group: checkpoint
      secret: checkpoint-secret
    - group: approver
      secret: approver-secret

rbac:
  roles:
    - role: approver
      resources:
        - endpoint: /approver/**
          verbs:
            - ALL
    - role: checkpoint
      resources:
        - endpoint: /registry/**
          verbs:
            - ALL
        - endpoint: /checkpoint/**
          verbs:
            - ALL
    - role: ADMIN
      resources:
        - endpoint: /**
          verbs:
            - ALL
logging.level:
  ph.devcon: debug
