spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat
  #    default-property-inclusion: non_empty
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

semaphore:
  url: https://api.semaphore.co/api/v4/messages
  key: ''

server:
  servlet:
    context-path: /api/v1

rapidpass:
  auth:
    apiKey:
      enabled: true
      key: dctx

qrmaster:
  skey: ***REMOVED***
  controlkey: controlsecretkey
  encryptionKey: ***REMOVED***
  masterKey: ***REMOVED***


jwt:
  secrets:
    - group: checkpoint
      secret: checkpoint-secret
    - group: approver
      secret: approver-secret

# configure rbac roles here
rbac:
  roles:
    - role: approver
      resources:
        # authenticating activate, active but allowing login as public
        - endpoint: /users/**/activate
          verbs:
            - ALL
        - endpoint: /users/**/active
          verbs:
            - ALL
          # breaks checkpoint - no security integration yet >.<
        #        - endpoint: /batch/**
        #          verbs:
        #            - ALL
        - endpoint: /registry/access-passes/**
          verbs:
            # GET, POST being used for registration
            - PUT # APPROVE/DENY
            - DELETE # APPROVE/DENY
        - endpoint: /registry/access-passes
          verbs:
            - ALL
#    - role: checkpoint
#      resources:
#        - endpoint: /batch/access-passes
#          verbs:
#            - GET
#        - endpoint: /checkpoint/**
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices/**
#          verbs:
#            - ALL

logging:
  level:
    ph.devcon: debug
    org:
      springframework:
        security: debug