spring:
  datasource:
    url: jdbc:postgresql://${RAPIDPASS_PG_HOST}:${RAPIDPASS_PG_PORT}/${RAPIDPASS_PG_DATABASE}
    username: ${RAPIDPASS_PG_USERNAME}
    password: ${RAPIDPASS_PG_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${RAPIDPASS_PG_HOST}:${RAPIDPASS_PG_PORT}/${RAPIDPASS_PG_DATABASE}
    user: ${RAPIDPASS_PG_USERNAME}
    password: ${RAPIDPASS_PG_PASSWORD}
  mail:
    host: ${RAPIDPASS_SMTP_HOST}
    port: ${RAPIDPASS_SMTP_PORT}
    username: ${RAPIDPASS_SMTP_USERNAME}
    password: ${RAPIDPASS_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${RAPIDPASS_SMTP_AUTH_ENABLED}
          starttls:
            enable: ${RAPIDPASS_SMTP_TLS_ENABLED}
semaphore:
  url: ${RAPIDPASS_SEMAPHORE_URL}
  key: ${RAPIDPASS_SEMAPHORE_KEY}

management:
  endpoint.prometheus.enabled: true
  endpoints.web.exposure.include: info,health,prometheus

rapidpass.jwt.secret: ${RAPIDPASS_JWT_SECRET}

qrmaster:
  skey: ${RAPIDPASS_QRMASTER_SKEY}
  controlkey: ${RAPIDPASS_QRMASTER_CONTROLKEY}
