spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat

  mail:
    host: smtp.mailgun.org
    port: 587
    username: rapidpass@talino.mg.amihan.net
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

testMobile: 09171234567
testEmail: test@gmail.com

security.enabled: true

jwt:
  secrets:
    - group: checkpoint
      secret: checkpoint-secret
    - group: approver
      secret: approver-secret

rbac:
  roles:
    - role: approver
      resources:
        # authenticating activate, active but allowing login as public
        - endpoint: /users/**/activate
          verbs:
            - ALL
        - endpoint: /users/**/active
          verbs:
            - ALL
          # breaks checkpoint - no security integration yet >.<
        #        - endpoint: /batch/**
        #          verbs:
        #            - ALL
        - endpoint: /registry/access-passes/?**
          verbs:
            - GET # used by approver only
            # POST # used for registration  DO NOT ENABLE!
            - PUT # APPROVE/DENY
            - DELETE # APPROVE/DENY
        - endpoint: /registry/access-passes
          verbs:
            - GET
            - PUT
            - DELETE
            # POST # used for registration  DO NOT ENABLE!
#    - role: checkpoint
#      resources:
#        - endpoint: /batch/access-passes
#          verbs:
#            - GET
#        - endpoint: /checkpoint/**
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices/**
#          verbs:
#            - ALL


logging.level:
  ph.devcon: debug
