spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

    date-format: com.devcon.rapidpass.utilities.RFC3339DateFormat
#    default-property-inclusion: non_empty


springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
