spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/rapidpass
    user: dctx
    password: password

qrmaster:
  skey: rapidmasterkey