spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat
  #    default-property-inclusion: non_empty
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers: rapidpass-kafka.eastasia.azurecontainer.io:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: rapidrequest_group
    producer:
      bootstrap-servers: localhost:9092
#      bootstrap-servers: rapidpass-kafka.eastasia.azurecontainer.io:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # needed for keycloak to override some security beans
  main:
    allow-bean-definition-overriding: true

topic:
  new-requests: rapidpass-requests
  new-registrar-user-requests: rapidpass-approver-requests
  approval-notifications: rapidpass-approvals
  rapidpass-events: rapidpass-events
  partitions-num: 3
  replication-factor: 1

kafka:
  enabled: false # enables or disables kafka event processing

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

semaphore:
  url: https://api.semaphore.co/api/v4/messages
  key: ''

server:
  servlet:
    context-path: /api/v1

rapidpass:
  auth:
    apiKey:
      enabled: true
      key: dctx
  expiration:
    year: 2020
    month: 5
    day: 15

endpointswitch:
  checkpoint:
    auth: true
  batch:
    accesspasses: false
  registry:
    accesspasses: false


qrmaster:
  skey: ${RAPIDPASS_QRMASTER_SKEY}
  controlkey: ${RAPIDPASS_QRMASTER_CONTROLKEY}
  encryptionKey: ${RAPIDPASS_ENCRYPTION_KEY}
  masterKey: ${RAPIDPASS_MASTER_KEY}


jwt:
  secrets:
    - group: checkpoint
      secret: checkpoint-secret
    - group: approver
      secret: approver-secret

# configure rbac roles here
rbac:
  roles:
    - role: approver
      resources:
        # authenticating activate, active but allowing login as public
        - endpoint: /users/**/activate
          verbs:
            - ALL
        - endpoint: /users/**/active
          verbs:
            - ALL
          # breaks checkpoint - no security integration yet >.<
        #        - endpoint: /batch/**
        #          verbs:
        #            - ALL
        - endpoint: /registry/access-passes/?**
          verbs:
            - GET # used by approver only
            # POST # used for registration  DO NOT ENABLE!
            - PUT # APPROVE/DENY
            - DELETE # APPROVE/DENY
        - endpoint: /registry/access-passes
          verbs:
            - GET
            - PUT
            - DELETE
            # POST # used for registration  DO NOT ENABLE!
#    - role: checkpoint
#      resources:
#        - endpoint: /batch/access-passes
#          verbs:
#            - GET
#        - endpoint: /checkpoint/**
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices
#          verbs:
#            - ALL
#        - endpoint: /registry/scanner-devices/**
#          verbs:
#            - ALL


security:
  enabled: true
  cors:
    allowedorigins:
      https://rapidpass.ph,https://dashboard.rapidpass.ph
  csp:
    srcs:
      script: "*.rapidpass.ph rapidpass.ph"

keycloak: # override me in env vars!
  auth-server-url: http://localhost:8180/auth/
  realm: rapidpass-api-local
  resource: rapidpass-api
  ssl-required: external
  credentials:
    secret: 22f20434-39cd-4e39-9620-99f99a6b0334


logging:
  level:
    ph.devcon: debug
    org:
      springframework:
        security: debug
      keycloak: debug