spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat

  mail:
    host: smtp.mailgun.org
    port: 587
    username: rapidpass@talino.mg.amihan.net
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: rapidrequest_group
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  main:
    banner-mode: OFF

topic:
  new-requests: rapidpass-requests
  new-registrar-user-requests: rapidpass-approver-requests
  approval-notifications: rapidpass-approvals
  rapidpass-events: rapidpass-events
  partitions-num: 3
  replication-factor: 1

kafka:
  enabled: false # enables or disables kafka event processing

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

semaphore:
  url: https://api.semaphore.co/api/v4/messages
  key: ''

server:
  servlet:
    context-path: /api/v1

rapidpass:
  auth:
    apiKey:
      enabled: true
      key: dctx
  expiration:
    year: 2020
    month: 5
    day: 15
  checkpointApkUrl: https://www.google.com/rapidpass-checkpoint-v1.4.apk
  checkpointApkHash: ABCDEF1234567890
  checkpointApkVersion: 1.4.0

endpointswitch:
  checkpoint:
    auth: true
  batch:
    accesspasses: false
  registry:
    accesspasses: false


qrmaster:
  # Master Key,Signing Key,Encryption Key,Valid To
  responseKeys[0]: 534f4d455f4d41535445525f4b4559,534f4d455f5349474e494e475f4b4559,534f4d455f454e4352595054494f4e5f4b4559,2020-06-30T08:00:00Z
  controlkey: ABCDEFGHIJKLMNO

logging:
  level:
    root: INFO
    ph.devcon: DEBUG
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG


keycloak-api:
  apiUsername: scanner-registrar@rapidpass.ph
  apiPassword: scanner-registrar@rapidpass.ph

keycloak: # override me in env vars!
  auth-server-url: http://localhost:8180/auth/
  realm: rapidpass
  resource: rapidpass-api
  ssl-required: external
  credentials.secret: '**********'
  bearer-only: true
  cors: true
  securityConstraints[0]:
    securityCollections[0]:
      name: OpenAPI Configuration
      patterns[0]: /swagger-ui.html
      patterns[1]: /registry/qr-codes/*
      patterns[2]: /checkpoint/auth
      patterns[3]: /checkpoint/register
      patterns[4]: /registry/access-passes/status/*
  securityConstraints[1]:
    authRoles[0]: user
    authRoles[1]: approver
    authRoles[2]: inspector
    securityCollections[0]:
      name: secured endpoints
      patterns[0]: /registry/*
      patterns[1]: /registry/access-passes/*
      patterns[2]: /batch/*
      patterns[3]: /tester/*
      patterns[4]: /users/*
      patterns[5]: /lookup/*
      patterns[6]: /checkpoint/*