spring:
  servlet:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidpass
    username: dctx
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: ph.devcon.rapidpass.utilities.RFC3339DateFormat
#    default-property-inclusion: non_empty
  mail:
    host: smtp.mailgun.org
    port: 587
    username: rapidpass@talino.mg.amihan.net
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

semaphore:
  url: https://api.semaphore.co/api/v4/messages
  key: ''

server:
  servlet:
    context-path: /api/v1
