openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jonasespelita/rapidpass-api/1.0.0
info:
  description: API for RapidPass web and mobile Applications.
  version: "2.0.1"
  title: RapidPass API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: inspector
    description: Endpoints for inspector app
  - name: pwa
    description: Endpoints for PWA/mobile end-user app
  - name: dashboard
    description: Endpoints for approval applications

paths:
  /api/v1/registry/accessPasses:
    post:
      tags:
        - pwa
        - dashboard
      summary: Creates a request for a new RapidPass, can be for individual or vehicle depending on pass type
      operationId: requestAccessPass
      description: |
        Called from the PWA or web site registration page to register a user.  All new access passes will have a status of 'pending'.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RapidPassRequest'
        description: Rapid Pass request payload.
      responses:
        '201':
          description: Request created
          content:
            application/json:
              schema:
                type: object
                properties:
                  referenceId:
                    type: string
                    description: backend generated reference id for the requested access pass
                description: reference id of the access pass
          links:
            GetAccessPassById:
              operationId: getAccessPassById
              parameters:
                referenceId: '$response.body#/referenceId'
        '400':
          description: Invalid Input
    get:
      tags:
        - dashboard
        - inspector
      summary: Gets a list of access passes
      operationId: listAccessPasses
      parameters:
        - name: status
          in: query
          required: false
          description: status of access passes to retrieve
          schema:
            type: string
        - name: validUntil
          in: query
          required: false
          description: returns a list of access passes that are valid until the specified date
          schema:
            type: string
      responses:
        '200':
          description: Status of the request pass
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    referenceId:
                      type: string
                    accessPass:
                      $ref: '#/components/schemas/AccessPass'
  /api/v1/batch/accessPasses:
    post:
      tags:
        - dashboard
      summary: Upload CSV/Excel file of approved control numbers TODO
      operationId: uploadAccessPasses
      responses:
        '200':
          description: Upload successful
  /api/v1/registry/controlCodes:
    get:
      tags:
        - inspector
        - dashboard
      summary: Downloads a list of approved control numbers
      operationId: downloadControlCodes
      responses:
        '200':
          description: list of all approved control numbers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - referenceId
                  properties:
                    referenceId:
                      type: string
                      description: backend generated reference id, created upon request
                    controlCode:
                      type: string
                      description: approved control control code
                    passType:
                      type: string
                      description: type of access pass
                    plateOrId:
                      type: string
                      description: plateNumber or id of associated with access pass
  /api/v1/registry/accessPasses/{referenceID}:
    get:
      tags:
        - inspector
        - pwa
        - dashboard
      summary: Get information about an access pass
      operationId: getAccessPassById
      parameters:
        - name: referenceID
          in: path
          description: Reference ID of the access pass request, mobile number for individuals and plate numbers for vehicles
          required: true
          schema:
            type: string
      responses:
        '200':
          description: More information on control number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessPass'
    put:
      tags:
        - dashboard
      summary: Approves or Declines a Rapid Pass request
      operationId: updateAccessPass
      parameters:
        - name: referenceID
          in: path
          description: Reference ID of the access pass request, mobile number for individuals and plate numbers for vehicles
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                referenceId:
                  type: string
                passType:
                  type: string
                plateOrId:
                  type: string
                validUntil:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: approves the Rapid Pass Request with referenced reference Number. Will generate a control code in system and send notifications to Requestor along with QR code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  referenceId:
                    type: string
                    description: backend generated reference id for the requested access pass
                description: reference id of the access pass
          links:
            GetAccessPassById:
              operationId: getAccessPassById
              parameters:
                referenceId: '$response.body#/referenceId'
    delete:
      tags:
        - dashboard
      summary: Suspends an active access pass
      operationId: suspendAccessPass
      parameters:
        - name: referenceID
          in: path
          description: Reference ID of the access pass request, mobile number for individuals and plate numbers for vehicles
          required: true
          schema:
            type: string
      responses:
        '200':
          description: approves the Rapid Pass Request with referenced reference Number. Will generate a control code in system and send notifications to Requestor along with QR code.

components:
  schemas:
    RapidPassRequest:
      type: object
      properties:
        passType:
          type: string
          description: Type of pass being requested. Can be individual or vehicle
        accessType:
          type: string
          description: Type of access needed. This is tied to gov agency that will approve pass
        name:
          type: string
          description: name of individual that will use the access pass
        company:
          type: string
          description: company of access pass holder
        idType:
          type: string
          description: for vehicles this could be plate number or conduction sticker, for individuals this will be the type of ID, e.g. company ID, driver's license, etc.
        plateOrId:
          type: string
          description: plate number of vehicle or ID of individual
        mobileNumber:
          type: string
          description: mobile number of access pass holder
        email:
          type: string
          description: email address of access pass holder
        originAddress:
          type: string
          description: general location where the requester is coming from
        destAddress:
          type: string
          description: general location where ther requester is heading to
        remarks:
          type: string

    AccessPass:
      allOf:
        - $ref: '#/components/schemas/RapidPassRequest'
        - properties:
            controlCode:
              type: string
              description: generated by the backend when a pass has been approved.
            status:
              type: string
              description: status of the access pass
            validUntil:
              type: string
              description: expiration date of the access pass
      type: object