openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tiongks/RapidPass-API/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jonasespelita/rapidpass-api/1.0.0
info:
  description: API for Rapid Pass Web Services. Guys, currently super simple pass ng API. Please send Merge Requests to update details. Thanks!
  version: "1.0.0"
  title: RapidPass API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: inspector
    description: Endpoints for inspector app
  - name: pwa
    description: Endpoints for PWA/mobile end-user app
  - name: dashboard
    description: Endpoints for approval applications

paths:
  /api/v1/registry/accessPasses:
    post:
      tags:
        - pwa
        - dashboard
      summary: Creates a request for a new RapidPass, can be for individual or vehicle depending on pass type
      operationId: register
      description: |
        Called from the PWA or web site registration page to register a user.  All new access passes will have a status of 'pending'.
      responses:
        '201':
          description: Request created
        '400':
          description: Invalid Input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRapidPassRequest'
        description: Rapid Pass request payload.
    get:
      tags:
        - dashboard
        - inspector
      summary: Gets a list of access passes
      parameters:
        - name: plateNum
          in: query
          required: false
          schema:
            type: string
        - name: mobileNum
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Status of the request pass
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status of request
  /api/v1/batch/accessPasses:
    post:
      tags:
        - dashboard
      summary: Upload CSV/Excel file of approved control numbers TODO
      responses:
        '200':
          description: Upload successful
  /api/v1/registry/controlCodes:
    get:
      tags:
        - inspector
        - dashboard
      summary: Downloads a list of approved control numbers
      responses:
        '200':
          description: list of all approved control numbers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - controlNum
                  properties:
                    controlNum:
                      type: string
                      description: approved control number
                    name:
                      type: string
                      description: name of approved pass
                    plateNum:
                      type: string
                      description: plateNumber of approved pass
  /api/v1/registry/accessPasses/{controlCode}:
    get:
      tags:
        - inspector
        - pwa
        - dashboard
      summary: Get information about an access pass
      parameters:
        - name: controlCode
          description: Control number to get more info on
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: More information on control number
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ApprovedRapidPass'
    put:
      tags:
        - dashboard
      summary: Approves or Declines a Rapid Pass request
      parameters:
        - name: referenceNumber
          description: Reference number of Rapid Pass request
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: approves the Rapid Pass Request with referenced reference Number. Will generate a control code in system and send notifications to Requestor along with QR code.
    delete:
      tags:
        - dashboard
      summary: Suspends an active access pass
      parameters:
        - name: referenceNumber
          description: Reference number of Rapid Pass request
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: approves the Rapid Pass Request with referenced reference Number. Will generate a control code in system and send notifications to Requestor along with QR code.

components:
  schemas:
    NewRapidPassRequest:
      type: object
      properties:
        passType:
          type: string
          description: Type of pass being requested. Can be individual or vehicle
        name:
          type: string
          description: Name of individual
        plateNum:
          type: string
          description: Plate Number of vehicle
        mobileNumber:
          type: string
          description: Mobile number of individual
        email:
          type: string
        destAddress:
          type: string
        company:
          type: string
        accessType:
          type: string
          description: Type of access needed. This is tied to gov agency that will approve pass
        idType:
          type: string
          description: for vehicles this could be plate number or conduction sticker, for individuals this will be the type of ID, e.g. company ID, driver's license, etc.
        idNumber:
          type: string
          description: ID number of presented ID Type

        remarks:
          type: string

    RapidPassRequest:
      allOf:
        - $ref: '#/components/schemas/RapidPassRequest'
        - properties:
            referenceNumber:
              type: string
              description: Backend only reference number. Populated by backend. Only generated when a pass has been successfuly requested.
      type: object
    ApprovedRapidPass:
      allOf:
        - $ref: '#/components/schemas/RapidPassRequest'
        - properties:
            controlCode:
              type: string
              description: Backend only control number. Populated by backend. This is used to create QR codes
      type: object