apiVersion: v1
kind: Service
metadata:
  name: {{ include "swaggerui.fullname" . }}
  labels:
    app: {{ template "swaggerui.name" . }}
    chart: {{ template "swaggerui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.swaggerUI.service.type }}
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: {{ template "swaggerui.name" . }}
    chart: {{ template "swaggerui.chart" . }}
